//
//  constants.swift
//  BookManager
//
//  Created by Naqui Darby on 2/26/26.
//


public let SETTINGS_THEME_KEY = "SETTINGS_THEME_KEY"
public let SETTINGS_GRID_COLUMNS_KEY = "SETTINGS_GRID_COLUMNS_KEY"
public let SETTINGS_ACCENT_COLOR_KEY = "SETTINGS_ACCENT_COLOR_KEY"
public let SETTINGS_FONT_SIZE_KEY = "SETTINGS_FONT_SIZE_KEY"
public let SETTINGS_SORT_KEY = "SETTINGS_SORT_KEY"
